### ISSUE TITLE
The multi-project build  throws a nullPointerException

### ISSUE THREAD

**Issue by seboo** [lutece-platform/lutece-dev-plugin-example#5]
The build failed when trying to build the project with a multi-project POM (step 6), using the command 
`mvn lutece:exploded -P multi-project`
 
lutece-maven-plugin throws a NullPointerException : 

`[ERROR] Failed to execute goal fr.paris.lutece.tools:lutece-maven-plugin:4.0.2:exploded (default-cli) on project plugin-mylutece: Execution default-cli of goal fr.paris.lutece.tools:lutece-maven-plugin:4.0.2:exploded failed. NullPointerException`

is it a lutece-maven-plugin issue ?

**Comment by jonenst** [comment]
This was fixed in global-pom 4.0.2 (using lutece-maven-plugin 4.0.3). Using it as a parent in all projects will fix the problem. Thanks !
